name: terca
description: "Aplicativo para encontrar locais acessíveis"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.5
  sqflite: ^2.0.0+4
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  provider: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_rating_bar: ^4.0.0
  firebase_messaging: ^15.1.5
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  firebase_database: any
  geocoding: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
